import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Fanar',
      link: {type: 'doc', id: 'fanar/index'},
      items: [{type: 'autogenerated', dirName: 'fanar'}],
    },
    {
      type: 'category',
      label: 'User Guide',
      link: {type: 'doc', id: 'user-guide/getting-started'},
      items: [{type: 'autogenerated', dirName: 'user-guide'}],
    },
    {
      type: 'category',
      label: 'Self-Hosted',
      link: {type: 'doc', id: 'self-hosted/setup'},
      items: [{type: 'autogenerated', dirName: 'self-hosted'}],
    },
    {
      type: 'category',
      label: 'Data Sources',
      link: {type: 'doc', id: 'data-sources/supported-data-sources'},
      items: [{type: 'autogenerated', dirName: 'data-sources'}],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [{type: 'autogenerated', dirName: 'faq'}],
    },
  ],
};

export default sidebars;
