import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'start'}],
    },
    {
      type: 'category',
      label: 'Ask Fanar',
      collapsed: false,
      link: {type: 'doc', id: 'ask/index'},
      items: [{type: 'autogenerated', dirName: 'ask'}],
    },
    {
      type: 'category',
      label: 'Build',
      items: [{type: 'autogenerated', dirName: 'build'}],
    },
    {
      type: 'category',
      label: 'Connect your data',
      link: {type: 'doc', id: 'connect/index'},
      items: [{type: 'autogenerated', dirName: 'connect'}],
    },
    {
      type: 'category',
      label: 'Administer',
      link: {type: 'doc', id: 'administer/index'},
      items: [{type: 'autogenerated', dirName: 'administer'}],
    },
    {
      type: 'category',
      label: 'Develop',
      link: {type: 'doc', id: 'develop/index'},
      items: [{type: 'autogenerated', dirName: 'develop'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
